### ISSUE TITLE
Sentry handler

### ISSUE THREAD

**Issue by lukasotocerny** [hackal/Exp#22]
I request adding a feature for sending runtime errors to Sentry.

Either I would have a default handler sending data to our own Exponea Sentry, or have a more generic capability of `handlers` (similar to handlers in loggers - see Node Winston or Python native logger), where you can specify transports for sending errors to - Sentry/buckets.

**Use case:** Especially in the beginning of Exp in production, we will be able to monitor Exp bugs. Later on, it's useful for debugging banners.

**Comment by hackal** [comment]
Great idea, I was thinking of just implementing custom `warn()` function that is called when we encounter an error, the function will integrate with sentry.

**Comment by lukasotocerny** [comment]
Addressed in https://github.com/hackal/Exp/pull/24

**Comment by lukasotocerny** [comment]
Solved in release https://github.com/hackal/Exp/releases/tag/v1.2.0
