### ISSUE TITLE
Adding project token, and banner_id and banner_name to sentry context prevents banners from loading

### ISSUE THREAD

**Issue by JuroOravec** [hackal/Exp#31]
On some occasions, banners do not load and do not get past this point. If I comment out the code that calls RavenInstance.setTagsContext, initialization of banner proceeds normally and banner loads.
tested on www.emps.fun, though I suppose the same issue might have been on bonuszbrigad too.

```
lines 116-122
                  if (settings.context.sdk._) {
                        this.RavenInstance.setTagsContext({
                            project_token: settings.context.sdk._[0][1][0].token
                        });
                    }
                    return settings.context.sdk;

lines 132-139
                   if (settings.context.data.banner_id && settings.context.data.banner_name) {
                        this.RavenInstance.setTagsContext({
                            banner_id: settings.context.data.banner_id,
                            banner_name: settings.context.data.banner_name
                        });
                    }
                    return settings.context.data;
```

**Comment by lukasotocerny** [comment]
I'll take a look on this.

**Comment by lukasotocerny** [comment]
I think I've solved it in here: https://github.com/hackal/Exp/tree/sentry-fix but still need to test it properly. Problem was with trying to set Raven tags even when Sentry was not initialised.

**Comment by lukasotocerny** [comment]
merged and resolved in https://github.com/hackal/Exp/pull/35
