### ISSUE TITLE
exp-bind should apply to innerHTML, not only to text

### ISSUE THREAD

**Issue by rkluvanec** [hackal/Exp#47]
Right now, you can only change the text of the bounded element, which doesn't support e.g. <br> or <hr> elements for better formatting.

**Comment by hackal** [comment]
Please could you add a specific use case? I would leave exp-bind as it is and add exp-html for this. We should also make sure that we are sanitizing the text of exp-bind properly.

To have better control over the text we have added formatters. See https://exp-framework.exponea.com/#formatters for more info.

**Comment by rkluvanec** [comment]
Adding exp-html actually makes more sense than combining these two in one function, good idea!

Example use-case is setting up a personalized form inside of a banner, where you could create a definition of each input field dynamically

**Comment by hackal** [comment]
#55 will be added in next release, thank you for suggestion
